# Generated by Django 3.2 on 2021-04-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('backdrop_path', models.CharField(blank=True, max_length=50)),
                ('poster_path', models.CharField(blank=True, max_length=50)),
                ('homepage', models.CharField(blank=True, max_length=100)),
                ('imdb_id', models.CharField(blank=True, max_length=15)),
                ('overview', models.TextField(blank=True)),
                ('runtime', models.IntegerField(blank=True)),
                ('release_date', models.CharField(max_length=10)),
                ('creatinon_date', models.DateTimeField(auto_now_add=True)),
                ('tagline', models.TextField(blank=True)),
                ('vote_average', models.FloatField(blank=True)),
                ('genres', models.ManyToManyField(blank=True, default=None, to='api.Genre')),
            ],
        ),
    ]
